### ISSUE TITLE
BG1 to SoD transition fails in v2.5

### ISSUE THREAD

**Issue by RoxanneSHS** [K4thos/EET#28]
A detailed description and my preliminary findings on the issue are here
http://baldursextendedworld.com/Vanilla_Forums/discussion/122/game-will-not-transition-to-sod#latest

I have also seen reports on some other forums about the failed transition but this is the first case where I could analyze some data. I used a modified cutscene script (just removing the spells) and it worked, so apparently the spells have some issues.

**Comment by RoxanneSHS** [comment]
Here is another report about the essential Global("EndofBG1","Global",1) not set on transition to SoD.
http://baldursextendedworld.com/Vanilla_Forums/discussion/125/in-sod-the-bg1-npcs-keep-initiating-conversation#latest
This may be a separate issue or a result of my hasty attempt to fix the first issue,
Anyway, adding this code (EXTEND_TOP...) may help to assure the global is always set

IF
Global("ENDOFBG1","GLOBAL",0)
Dead("Sarevok")
Global("EnteredTempleBhaal","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("ENDOFBG1","GLOBAL",1)
END

**Comment by RoxanneSHS** [comment]
Some more research and testing with some other users have led to this solution.
To take into account the behaviour of the spells used and other actions performed during the transition script, a re-ordering of events solves the problems with stuck transitions. The resulting cutscene script is this
[BDSODTRN.zip](https://github.com/K4thos/EET/files/2486604/BDSODTRN.zip)

I am not doing a pull request because you have your own method of changing scripts in EET.

**Comment by K4thos** [comment]
can't reproduce it on clean EET using the save file provided in the linked topic, so the problem lays in some other mod. If mod breaks the sod transition than it should be reported to the modder, not here., since the same problem would happen on vanilla BG:EE+SoD installation where the exact same code is used. The only thing EET changes in this script is "endcrdit" movie playback removal and changed ENDOFBG1 value from 2 to 1.
